import { Lesson } from '../types';

// Конфигурация уроков (можно легко редактировать)
export const LESSONS: Lesson[] = [
  {
    id: 1,
    title: 'Урок 1: Введение в ОГЭ по русскому языку',
    description: 'Структура экзамена, критерии оценивания, стратегия подготовки',
    videoUrl: 'https://www.youtube.com/watch?v=example1',
    materialUrl: 'https://docs.google.com/document/d/example1',
    tasks: [
      {
        id: 'l1-t1',
        name: 'Тест: Знакомство со структурой ОГЭ',
        type: 'external',
        url: 'https://forms.google.com/example1',
        reward: 2,
        maxScore: 10,
      },
      {
        id: 'l1-t2',
        name: 'Практика: Работа с КИМами',
        type: 'external',
        url: 'https://forms.google.com/example2',
        reward: 3,
        maxScore: 15,
      },
    ],
    totalReward: 5,
    unlockType: 'date',
    unlockDate: '2024-01-01',
  },
  {
    id: 2,
    title: 'Урок 2: Орфография — приставки ПРЕ-/ПРИ-',
    description: 'Правописание приставок ПРЕ- и ПРИ-, практические задания',
    videoUrl: 'https://www.youtube.com/watch?v=example2',
    materialUrl: 'https://docs.google.com/document/d/example2',
    tasks: [
      {
        id: 'l2-t1',
        name: 'Теория: ПРЕ-/ПРИ-',
        type: 'external',
        url: 'https://forms.google.com/example3',
        reward: 2,
        maxScore: 12,
      },
      {
        id: 'l2-t2',
        name: 'Тренажёр: ПРЕ-/ПРИ-',
        type: 'external',
        url: 'https://quizlet.com/example1',
        reward: 2,
        maxScore: 20,
      },
    ],
    totalReward: 4,
    unlockType: 'progress',
    requiredLessons: [1],
  },
  {
    id: 3,
    title: 'Урок 3: Орфография — Н/НН в суффиксах',
    description: 'Правописание Н и НН в прилагательных, причастиях и наречиях',
    videoUrl: 'https://www.youtube.com/watch?v=example3',
    materialUrl: 'https://docs.google.com/document/d/example3',
    tasks: [
      {
        id: 'l3-t1',
        name: 'Тест: Н/НН в разных частях речи',
        type: 'external',
        url: 'https://forms.google.com/example4',
        reward: 3,
        maxScore: 15,
      },
      {
        id: 'l3-t2',
        name: 'Практика: Н/НН комплексно',
        type: 'external',
        url: 'https://forms.google.com/example5',
        reward: 3,
        maxScore: 20,
      },
    ],
    totalReward: 6,
    unlockType: 'both',
    unlockDate: '2024-01-10',
    requiredLessons: [2],
  },
  {
    id: 4,
    title: 'Урок 4: Пунктуация — однородные члены',
    description: 'Запятые при однородных членах предложения, союзы',
    videoUrl: 'https://www.youtube.com/watch?v=example4',
    materialUrl: 'https://docs.google.com/document/d/example4',
    tasks: [
      {
        id: 'l4-t1',
        name: 'Теория: Однородные члены',
        type: 'external',
        url: 'https://forms.google.com/example6',
        reward: 2,
        maxScore: 10,
      },
      {
        id: 'l4-t2',
        name: 'Тренажёр: Расстановка запятых',
        type: 'external',
        url: 'https://forms.google.com/example7',
        reward: 3,
        maxScore: 18,
      },
    ],
    totalReward: 5,
    unlockType: 'progress',
    requiredLessons: [3],
  },
  {
    id: 5,
    title: 'Урок 5: Пунктуация — обособленные члены',
    description: 'Причастные и деепричастные обороты, обособление',
    videoUrl: 'https://www.youtube.com/watch?v=example5',
    materialUrl: 'https://docs.google.com/document/d/example5',
    tasks: [
      {
        id: 'l5-t1',
        name: 'Тест: Причастные обороты',
        type: 'external',
        url: 'https://forms.google.com/example8',
        reward: 3,
        maxScore: 15,
      },
      {
        id: 'l5-t2',
        name: 'Тест: Деепричастные обороты',
        type: 'external',
        url: 'https://forms.google.com/example9',
        reward: 3,
        maxScore: 15,
      },
    ],
    totalReward: 6,
    unlockType: 'progress',
    requiredLessons: [4],
  },
  {
    id: 6,
    title: 'Урок 6: Сложные предложения — ССП и СПП',
    description: 'Сложносочинённые и сложноподчинённые предложения',
    videoUrl: 'https://www.youtube.com/watch?v=example6',
    materialUrl: 'https://docs.google.com/document/d/example6',
    tasks: [
      {
        id: 'l6-t1',
        name: 'Тест: ССП',
        type: 'external',
        url: 'https://forms.google.com/example10',
        reward: 2,
        maxScore: 12,
      },
      {
        id: 'l6-t2',
        name: 'Тест: СПП',
        type: 'external',
        url: 'https://forms.google.com/example11',
        reward: 3,
        maxScore: 18,
      },
    ],
    totalReward: 5,
    unlockType: 'progress',
    requiredLessons: [5],
  },
  {
    id: 7,
    title: 'Урок 7: Бессоюзные сложные предложения (БСП)',
    description: 'Знаки препинания в БСП: запятая, точка с запятой, двоеточие, тире',
    videoUrl: 'https://www.youtube.com/watch?v=example7',
    materialUrl: 'https://docs.google.com/document/d/example7',
    tasks: [
      {
        id: 'l7-t1',
        name: 'Теория: БСП',
        type: 'external',
        url: 'https://forms.google.com/example12',
        reward: 3,
        maxScore: 15,
      },
      {
        id: 'l7-t2',
        name: 'Практика: Комплексный анализ',
        type: 'external',
        url: 'https://forms.google.com/example13',
        reward: 3,
        maxScore: 20,
      },
    ],
    totalReward: 6,
    unlockType: 'progress',
    requiredLessons: [6],
  },
  {
    id: 8,
    title: 'Урок 8: Речевые нормы и стилистика',
    description: 'Паронимы, плеоназм, стилистические ошибки',
    videoUrl: 'https://www.youtube.com/watch?v=example8',
    materialUrl: 'https://docs.google.com/document/d/example8',
    tasks: [
      {
        id: 'l8-t1',
        name: 'Тест: Паронимы',
        type: 'external',
        url: 'https://forms.google.com/example14',
        reward: 2,
        maxScore: 10,
      },
      {
        id: 'l8-t2',
        name: 'Тест: Речевые ошибки',
        type: 'external',
        url: 'https://forms.google.com/example15',
        reward: 3,
        maxScore: 15,
      },
    ],
    totalReward: 5,
    unlockType: 'progress',
    requiredLessons: [7],
  },
  {
    id: 9,
    title: 'Урок 9: Изложение — работа с текстом',
    description: 'Техника сжатия текста, выделение микротем, средства связи',
    videoUrl: 'https://www.youtube.com/watch?v=example9',
    materialUrl: 'https://docs.google.com/document/d/example9',
    tasks: [
      {
        id: 'l9-t1',
        name: 'Практика: Сжатие текста',
        type: 'external',
        url: 'https://forms.google.com/example16',
        reward: 3,
        maxScore: 20,
      },
      {
        id: 'l9-t2',
        name: 'Практика: Микротемы',
        type: 'external',
        url: 'https://forms.google.com/example17',
        reward: 3,
        maxScore: 15,
      },
    ],
    totalReward: 6,
    unlockType: 'progress',
    requiredLessons: [8],
  },
  {
    id: 10,
    title: 'Урок 10: Сочинение-рассуждение 9.3',
    description: 'Структура сочинения, аргументация, цитирование',
    videoUrl: 'https://www.youtube.com/watch?v=example10',
    materialUrl: 'https://docs.google.com/document/d/example10',
    tasks: [
      {
        id: 'l10-t1',
        name: 'Тест: Структура сочинения',
        type: 'external',
        url: 'https://forms.google.com/example18',
        reward: 2,
        maxScore: 10,
      },
      {
        id: 'l10-t2',
        name: 'Практика: Написание сочинения',
        type: 'external',
        url: 'https://forms.google.com/example19',
        reward: 5,
        maxScore: 30,
      },
    ],
    totalReward: 7,
    unlockType: 'progress',
    requiredLessons: [9],
  },
];

export const getLessonById = (id: number): Lesson | undefined => {
  return LESSONS.find(l => l.id === id);
};
